support callback in upload/import
wix/media-platform-java-sdk pull request #34
Opened 2020-12-16 10:48 UTC by lelikg

#pr
review by '@'elad

2020-12-17 13:13 UTC, golanpa approved these changes

2021-01-04 12:20 UTC, Elad-Laufer requested changes

2021-01-04 12:20 UTC, Elad-Laufer commented on src/test/resources/__files/file-upload-with-callback-response.json
> +    "callback" : {
The upload response is a FileDescriptor, which does not have a 'callback' property.

2021-01-04 12:59 UTC, lelikg commented on src/test/resources/__files/file-upload-with-callback-response.json
> +    "callback" : {
fixed

2021-01-04 15:20 UTC, Elad-Laufer approved these changes

2021-01-04 20:04 UTC, merged